/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedAnalysisRouteImport } from './routes/_authenticated/analysis'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedRulesRouteImport } from './routes/_authenticated/rules'
import { Route as AuthenticatedAdminSetupRouteImport } from './routes/_authenticated/admin.setup'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedTransactionsIndexRouteImport } from './routes/_authenticated/transactions.index'
import { Route as AuthenticatedTransactionsIdRouteImport } from './routes/_authenticated/transactions.$id'
import { Route as AuthenticatedTransactionsNewRouteImport } from './routes/_authenticated/transactions.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalysisRoute = AuthenticatedAnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRulesRoute = AuthenticatedRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminSetupRoute = AuthenticatedAdminSetupRouteImport.update({
  id: '/admin/setup',
  path: '/admin/setup',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTransactionsIndexRoute =
  AuthenticatedTransactionsIndexRouteImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTransactionsIdRoute =
  AuthenticatedTransactionsIdRouteImport.update({
    id: '/transactions/$id',
    path: '/transactions/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTransactionsNewRoute =
  AuthenticatedTransactionsNewRouteImport.update({
    id: '/transactions/new',
    path: '/transactions/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/analysis': typeof AuthenticatedAnalysisRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/rules': typeof AuthenticatedRulesRoute
  '/admin/setup': typeof AuthenticatedAdminSetupRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/transactions/$id': typeof AuthenticatedTransactionsIdRoute
  '/transactions/new': typeof AuthenticatedTransactionsNewRoute
  '/transactions/': typeof AuthenticatedTransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/analysis': typeof AuthenticatedAnalysisRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/rules': typeof AuthenticatedRulesRoute
  '/admin/setup': typeof AuthenticatedAdminSetupRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/transactions/$id': typeof AuthenticatedTransactionsIdRoute
  '/transactions/new': typeof AuthenticatedTransactionsNewRoute
  '/transactions': typeof AuthenticatedTransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/register': typeof RegisterRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/analysis': typeof AuthenticatedAnalysisRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/rules': typeof AuthenticatedRulesRoute
  '/_authenticated/admin/setup': typeof AuthenticatedAdminSetupRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/transactions/$id': typeof AuthenticatedTransactionsIdRoute
  '/_authenticated/transactions/new': typeof AuthenticatedTransactionsNewRoute
  '/_authenticated/transactions/': typeof AuthenticatedTransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/register'
    | '/alerts'
    | '/analysis'
    | '/dashboard'
    | '/reports'
    | '/rules'
    | '/admin/setup'
    | '/admin/users'
    | '/transactions/$id'
    | '/transactions/new'
    | '/transactions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/alerts'
    | '/analysis'
    | '/dashboard'
    | '/reports'
    | '/rules'
    | '/admin/setup'
    | '/admin/users'
    | '/transactions/$id'
    | '/transactions/new'
    | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/register'
    | '/_authenticated/alerts'
    | '/_authenticated/analysis'
    | '/_authenticated/dashboard'
    | '/_authenticated/reports'
    | '/_authenticated/rules'
    | '/_authenticated/admin/setup'
    | '/_authenticated/admin/users'
    | '/_authenticated/transactions/$id'
    | '/_authenticated/transactions/new'
    | '/_authenticated/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analysis': {
      id: '/_authenticated/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AuthenticatedAnalysisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rules': {
      id: '/_authenticated/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof AuthenticatedRulesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/setup': {
      id: '/_authenticated/admin/setup'
      path: '/admin/setup'
      fullPath: '/admin/setup'
      preLoaderRoute: typeof AuthenticatedAdminSetupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transactions/': {
      id: '/_authenticated/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof AuthenticatedTransactionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transactions/$id': {
      id: '/_authenticated/transactions/$id'
      path: '/transactions/$id'
      fullPath: '/transactions/$id'
      preLoaderRoute: typeof AuthenticatedTransactionsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transactions/new': {
      id: '/_authenticated/transactions/new'
      path: '/transactions/new'
      fullPath: '/transactions/new'
      preLoaderRoute: typeof AuthenticatedTransactionsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedAnalysisRoute: typeof AuthenticatedAnalysisRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedRulesRoute: typeof AuthenticatedRulesRoute
  AuthenticatedAdminSetupRoute: typeof AuthenticatedAdminSetupRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedTransactionsIdRoute: typeof AuthenticatedTransactionsIdRoute
  AuthenticatedTransactionsNewRoute: typeof AuthenticatedTransactionsNewRoute
  AuthenticatedTransactionsIndexRoute: typeof AuthenticatedTransactionsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedAnalysisRoute: AuthenticatedAnalysisRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedRulesRoute: AuthenticatedRulesRoute,
  AuthenticatedAdminSetupRoute: AuthenticatedAdminSetupRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedTransactionsIdRoute: AuthenticatedTransactionsIdRoute,
  AuthenticatedTransactionsNewRoute: AuthenticatedTransactionsNewRoute,
  AuthenticatedTransactionsIndexRoute: AuthenticatedTransactionsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
